name: GithubAction
on: [push]
jobs:
  Test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - name: Test SimpleTest
       run: 
          cat ${{ github.workspace }}/hw1/MyTest1.java
